[package]
name = "shared_spendings"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
chrono = "0.4.39"
diesel = { version = "2.2.7", features = ["chrono", "postgres"] } 
dotenvy = "0.15.7"
serde = "1.0.217"
